spring.application.name=Session05_b3
# URL k?t n?i H2 (ch? ?? in-memory)
spring.datasource.url=jdbc:h2:mem:testdb

# N?u mu?n l?u file DB tr�n ? ??a
# spring.datasource.url=jdbc:h2:file:./data/testdb

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Cho ph�p truy c?p console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console